### ISSUE TITLE
the error message ("incorrect visualization") instead of the extension...

### ISSUE THREAD

**Issue by herrhexer** [q2g/q2g-ext-scramble#24]
I don't know why but both in Qlik Sense Desktop and Server I see the error message ("incorrect visualization") instead of the extension...

![image](https://user-images.githubusercontent.com/30800211/39017811-8f7c9a84-4424-11e8-9b2c-fa7c635fb67e.png)

**Comment by konne** [comment]
I believe you just cloned the github repo. You have to compile it like it written in the readme.
Or you can download here the binary: https://m.sense2go.net/extension-package
