### ISSUE TITLE
Extension shows "Invalid Visualisation"  when i try and use in Desktop or Sever

### ISSUE THREAD

**Issue by danieldoheny** [q2g/q2g-ext-scramble#9]
Hi Konrad,

This looks like a great extension and would be very keen to use. The problem i have is when i add the extension to either Desktop or Server i get an error within the editor (see image)
![image](https://user-images.githubusercontent.com/34337492/33709773-60fac7fa-db36-11e7-9363-b7302ad27bfb.png)

It imports through the QMC without errors. I also checked in dev-hub to see if it was anything obvious. Upon opening the extension it errors (see image) 
![image](https://user-images.githubusercontent.com/34337492/33709852-a879925a-db36-11e7-8464-b85356c52d5f.png)

Any help would be great as this would be perfect for Demos.

Thanks in advance

**Comment by konne** [comment]
Hi,
you have to compile that extions with npm.
If you download it from source with installed nodeJS and the commands
   npm install
   npm run build
The current source code is still not production ready, but we hope to get it finished to the end of the week.

**Comment by danieldoheny** [comment]
Thank you for the Quick Response. I will try that.

**Comment by konne** [comment]
@danieldoheny you can also download the pre compile packages: https://m.sense2go.net/extension-package
